[infer_empty_array]
level = "Error"
message = "Cannot infer type of empty array"

[non_numeric_operand]
level = "Error"
message = "Cannot apply operator `{operator}` to non-numeric operand"

[deref_non_pointer]
level = "Error"
message = "Cannot dereference non-pointer type `{type}`"

[method_not_found]
level = "Error"
message = "Method `{method}` not found on type `{type}`"

[call_non_function]
level = "Error"
message = "Cannot call non-function expression"

[unexpected_parameters]
level = "Error"
message = "Expected {expected} parameter{s}, found {found}"

[unexpected_generic_args]
level = "Error"
message = "Expected {expected} generic argument{s}, found {found}"

[unknown_field]
level = "Error"
message = "Unknown field `{field}` on type `{type}`"

[missing_field]
level = "Error"
message = "Missing field `{field}` on type `{type}`"

[type_with_no_fields]
level = "Error"
message = "Cannot access field `{field}` on type `{type}` which has no fields"

[unknown_field_in_slice]
level = "Error"
message = "Unknown field `{field}` on slice"

[impl_expected_path_to_struct]
level = "Error"
message = "Expected path to struct in impl, found `{type}`"

[impl_expected_path_to_trait]
level = "Error"
message = "Expected path to trait in impl, found `{type}`"

[conflicting_implementations]
level = "Error"
message = "Conflicting implementations of `{trait}` for `{struct}`"

[missing_implementation]
level = "Error"
message = "Missing implementation of trait method `{method}`"

[signature_mismatch]
level = "Error"
message = "Signature mismatch in method `{method}`"

[type_mismatch]
level = "Error"
message = "Type mismatch: expected `{expected}`, found `{found}`"

[type_alias_not_struct]
level = "Error"
message = "Type alias `{name}` cannot be used in a struct literal because it does not resolve to a struct"

[recursive_type]
level = "Error"
message = "Recursive type detected"

[cannot_index]
level = "Error"
message = "Cannot index into non-array type `{type}`"

[unresolved_expression]
level = "Error"
message = "Could not resolve expression"

[unresolved_assoc_type]
level = "Error"
message = "Could not resolve associated type"
