[invalid_operator]
level = "Error"
message = "Invalid {kind} operator"

[expected_path_to_struct]
level = "Error"
message = "Expected path to struct, found `{path}`"

[expected_path_to_trait]
level = "Error"
message = "Expected path to trait, found `{path}`"

[expected_type_found_trait]
level = "Error"
message = "Expected type, found trait `{trait}`"
