[duplicate_definition]
level = "Error"
message = "Duplicate definition of `{item}` in `{scope}`"

[extern_function_body]
level = "Error"
message = "Extern functions cannot have a body"

[non_extern_function_body]
level = "Error"
message = "Non-extern function must have a body"

[tail_expr_not_at_tail]
level = "Error"
message = "Expression without semicolon must be at the end of a block"

[duplicate_field]
level = "Error"
message = "Duplicate field `{field}` in struct instantiation"

[return_outside_function]
level = "Error"
message = "Return statement outside of function"

[break_outside_loop]
level = "Error"
message = "Break statement outside of loop"

[invalid_assignment_target]
level = "Error"
message = "Invalid assignment target"

[invalid_index_target]
level = "Error"
message = "Invalid index target"

[generic_default_before]
level = "Error"
message = "Generic parameters with defaults must come after all required parameters"
