#!/bin/sh

set -e

echo '+cargo fmt -- --check'
cargo fmt -- --check

echo '+cargo run --manifest-path crates/oxic_diag_lint/Cargo.toml -- src/'
cargo run --manifest-path crates/oxic_diag_lint/Cargo.toml -- src/
